// 公共
export const PUBLIC = {
    SET_PAGE_TITLE: 'SET_PAGE_TITLE'
}

export const APPLY = {
    APPLY_INIT_PERSON: 'APPLY_INIT_PERSON',
    APPLY_ADD_PERSON: 'APPLY_ADD_PERSON',
    APPLY_DEL_PERSON: 'APPLY_DEL_PERSON',
    APPLY_EDIT_PERSON: 'APPLY_EDIT_PERSON'
}

// 活动
export const Activity = {
    GET_LIST: 'ACTIVITY_GET_LIST',
    ADD_DATA: 'ACTIVITY_ADD_DATA'
}
